import json
from datetime import datetime
from collections import Counter

# Load scan results
with open('data/automated_scan_results.json', 'r') as f:
    data = json.load(f)

# Generate executive summary
def generate_executive_summary():
    
    print("=" * 80)
    print(" " * 20 + "🏢 EXECUTIVE SECURITY SUMMARY")
    print("=" * 80)
    
    print(f"\n📅 Report Date: {datetime.now().strftime('%B %d, %Y at %H:%M')}")
    print(f"🎯 Target System: {data['target']}")
    print(f"📊 Scan Type: Web Application Security Assessment (OWASP ZAP)")
    
    # Overall Security Posture
    print("\n" + "-" * 80)
    print("📈 OVERALL SECURITY POSTURE")
    print("-" * 80)
    
    risk_score = data['risk_score']
    total_alerts = data['total_alerts']
    
    if risk_score > 25:
        posture = "🔴 CRITICAL"
        recommendation = "Immediate action required"
        color = "RED"
    elif risk_score > 15:
        posture = "🟠 HIGH RISK"
        recommendation = "Urgent remediation needed"
        color = "ORANGE"
    elif risk_score > 8:
        posture = "🟡 MODERATE RISK"
        recommendation = "Schedule remediation within 30 days"
        color = "YELLOW"
    else:
        posture = "🟢 LOW RISK"
        recommendation = "Continue monitoring"
        color = "GREEN"
    
    print(f"\nSecurity Status: {posture}")
    print(f"Risk Score: {risk_score}/30")
    print(f"Total Vulnerabilities: {total_alerts}")
    print(f"Recommendation: {recommendation}")
    
    # Risk Breakdown
    print("\n" + "-" * 80)
    print("📊 VULNERABILITY BREAKDOWN BY SEVERITY")
    print("-" * 80)
    
    risks = Counter([alert['risk'] for alert in data['alerts']])
    
    risk_order = {'High': 0, 'Medium': 1, 'Low': 2, 'Informational': 3}
    for risk in sorted(risks.keys(), key=lambda x: risk_order.get(x, 99)):
        count = risks[risk]
        bar = "█" * count
        print(f"{risk:15} | {bar} ({count})")
    
    # Top 3 Critical Findings
    print("\n" + "-" * 80)
    print("🚨 TOP 3 CRITICAL FINDINGS")
    print("-" * 80)
    
    risk_weights = {'High': 10, 'Medium': 5, 'Low': 2, 'Informational': 1}
    sorted_alerts = sorted(data['alerts'], 
                          key=lambda x: risk_weights.get(x['risk'], 0), 
                          reverse=True)
    
    for i, alert in enumerate(sorted_alerts[:3], 1):
        print(f"\n{i}. {alert['alert']}")
        print(f"   Severity: {alert['risk']}")
        print(f"   Impact: {alert['description'][:100]}...")
        print(f"   Affected URL: {alert['url'][:60]}...")
    
    # Business Impact Assessment
    print("\n" + "-" * 80)
    print("💼 BUSINESS IMPACT ASSESSMENT")
    print("-" * 80)
    
    high_count = risks.get('High', 0)
    medium_count = risks.get('Medium', 0)
    
    if high_count > 0:
        print(f"\n⚠️  {high_count} HIGH severity vulnerabilities detected:")
        print("   • Potential for data breach")
        print("   • Risk of unauthorized access")
        print("   • Possible service disruption")
        print("   • Compliance violations likely")
    
    if medium_count > 0:
        print(f"\n⚠️  {medium_count} MEDIUM severity vulnerabilities detected:")
        print("   • Increased attack surface")
        print("   • Potential security misconfigurations")
        print("   • Risk of information disclosure")
    
    # Cost Estimate (Industry Average)
    print("\n" + "-" * 80)
    print("💰 ESTIMATED REMEDIATION EFFORT")
    print("-" * 80)
    
    estimated_hours = (high_count * 8) + (medium_count * 4) + (risks.get('Low', 0) * 2)
    print(f"\nEstimated Development Hours: {estimated_hours}h")
    print(f"Estimated Timeline: {max(1, estimated_hours // 40)} week(s)")
    print(f"Recommended Team Size: {max(1, high_count // 3 + 1)} developer(s)")
    
    # Action Plan
    print("\n" + "-" * 80)
    print("📋 RECOMMENDED ACTION PLAN")
    print("-" * 80)
    
    print("\n🎯 IMMEDIATE (Week 1):")
    print("   1. Review and validate all HIGH severity findings")
    print("   2. Implement emergency security patches")
    print("   3. Restrict access to vulnerable endpoints")
    
    print("\n🎯 SHORT-TERM (Weeks 2-4):")
    print("   1. Remediate all HIGH and MEDIUM vulnerabilities")
    print("   2. Deploy security header configurations")
    print("   3. Update security policies and procedures")
    
    print("\n🎯 LONG-TERM (Months 2-3):")
    print("   1. Address LOW severity items")
    print("   2. Implement continuous security scanning")
    print("   3. Conduct security awareness training")
    print("   4. Schedule quarterly penetration tests")
    
    # Sign-off
    print("\n" + "=" * 80)
    print("Report Generated by: Adaptive Threat Detection System v2.0")
    print(f"Next Scan Recommended: {get_next_scan_date()}")
    print("=" * 80 + "\n")
    
    # Save to file
    save_summary_to_file()

def get_next_scan_date():
    from datetime import timedelta
    next_scan = datetime.now() + timedelta(days=30)
    return next_scan.strftime('%B %d, %Y')

def save_summary_to_file():
    filename = f"executive_reports/summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    # This would save the summary to a text file
    print(f"[✓] Summary can be saved to: {filename}")

if __name__ == "__main__":
    generate_executive_summary()
